require: rubocop-rails

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Style/FormatString:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
