FROM ruby:3.3.4

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential curl default-libmysqlclient-dev git libvips pkg-config unzip

ENV BUN_INSTALL=/usr/local/bun
ENV PATH=/usr/local/bun/bin:$PATH
ARG BUN_VERSION=1.1.26
RUN curl -fsSL https://bun.sh/install | bash -s -- "bun-v${BUN_VERSION}"

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY package.json bun.lockb ./
RUN bun install

COPY . .

RUN useradd rails --create-home --shell /bin/bash && \
    chown -R rails:rails /rails /usr/local
USER rails:rails

EXPOSE 3000

ENTRYPOINT ["bin/dev"]
